name: Atualizar Changelog Automatico

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gerar CHANGELOG.md Automatico
        uses: github-changelog-generator/github-changelog-generator@v1.16.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commitar alteracao do Changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: atualiza CHANGELOG.md [skip ci]"
          file_pattern: CHANGELOG.md